### ISSUE TITLE
Error when trying to run the editor on Linux/Mono

### ISSUE THREAD

**Issue by eugeneia** [AshleyF/Color#1]
Hi @AshleyF,

I get the following error when trying to run the editor:

```
Unhandled Exception:
System.ArgumentOutOfRangeException: Value must be positive and below the buffer height.
Parameter name: top
  at System.TermInfoDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x0004d] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.ConsoleDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Console.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Console+write@53-1.Invoke (System.Int32 x, System.Int32 y, System.Tuple`3[T1,T2,T3] tupledArg) [0x000e5] in <589cb8275d75245ba745038327b89c58>:0 
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V,W] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2, V arg3) [0x0000d] in <589cb6cadff9fae1a7450383cab69c58>:0 
  at Console.consoleRefresh () [0x0004d] in <589cb8275d75245ba745038327b89c58>:0 
  at Editor.render (Editor+State state) [0x00059] in <589cb8352df31a0ca745038335b89c58>:0 
  at Editor.main[a] (Editor+State state) [0x00014] in <589cb8352df31a0ca745038335b89c58>:0 
  at <StartupCode$Editor>.$Editor.main@ () [0x00044] in <589cb8352df31a0ca745038335b89c58>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException: Value must be positive and below the buffer height.
Parameter name: top
  at System.TermInfoDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x0004d] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.ConsoleDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Console.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Console+write@53-1.Invoke (System.Int32 x, System.Int32 y, System.Tuple`3[T1,T2,T3] tupledArg) [0x000e5] in <589cb8275d75245ba745038327b89c58>:0 
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V,W] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2, V arg3) [0x0000d] in <589cb6cadff9fae1a7450383cab69c58>:0 
  at Console.consoleRefresh () [0x0004d] in <589cb8275d75245ba745038327b89c58>:0 
  at Editor.render (Editor+State state) [0x00059] in <589cb8352df31a0ca745038335b89c58>:0
  at Editor.main[a] (Editor+State state) [0x00014] in <589cb8352df31a0ca745038335b89c58>:0 
  at <StartupCode$Editor>.$Editor.main@ () [0x00044] in <589cb8352df31a0ca745038335b89c58>:0 
```

Could you give me some pointers on how to run the Editor and Assembler?

**Comment by AshleyF** [comment]
Fixed! Sorry it took so long...

**Comment by AshleyF** [comment]
https://github.com/AshleyF/Color/commit/4a439ec71467261f4afe89c163d63e0cd49c4040

**Comment by eugeneia** [comment]
I pulled from master, did `xbuild Color.sln`, which in fact rebuilt `Editor.exe`, but I still get the exact same error (I am trying to launch the editor using `mono Editor/bin/Debug/Editor.exe`, am I doing it right?):

```
Unhandled Exception:
System.ArgumentOutOfRangeException: Value must be positive and below the buffer height.
Parameter name: top
  at System.TermInfoDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x0004d] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.ConsoleDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Console.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Console+write@53-1.Invoke (System.Int32 x, System.Int32 y, System.Tuple`3[T1,T2,T3] tupledArg) [0x000e5] in <590bb7465d75245ba745038346b70b59>:0 
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V,W] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2, V arg3) [0x0000d] in <589cb6cadff9fae1a7450383cab69c58>:0 
  at Console.consoleRefresh () [0x0004d] in <590bb7465d75245ba745038346b70b59>:0 
  at Editor.render (Editor+State state) [0x00059] in <590bb7502df31a0ca745038350b70b59>:0 
  at Editor.main[a] (Editor+State state) [0x00014] in <590bb7502df31a0ca745038350b70b59>:0 
  at <StartupCode$Editor>.$Editor.main@ () [0x00044] in <590bb7502df31a0ca745038350b70b59>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException: Value must be positive and below the buffer height.
Parameter name: top
  at System.TermInfoDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x0004d] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.ConsoleDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Console.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Console+write@53-1.Invoke (System.Int32 x, System.Int32 y, System.Tuple`3[T1,T2,T3] tupledArg) [0x000e5] in <590bb7465d75245ba745038346b70b59>:0 
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V,W] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2, V arg3) [0x0000d] in <589cb6cadff9fae1a7450383cab69c58>:0 
  at Console.consoleRefresh () [0x0004d] in <590bb7465d75245ba745038346b70b59>:0 
  at Editor.render (Editor+State state) [0x00059] in <590bb7502df31a0ca745038350b70b59>:0 
  at Editor.main[a] (Editor+State state) [0x00014] in <590bb7502df31a0ca745038350b70b59>:0 
  at <StartupCode$Editor>.$Editor.main@ () [0x00044] in <590bb7502df31a0ca745038350b70b59>:0
```

**Comment by AshleyF** [comment]
Hummm... I can repro a different error (`FileNotFound`) with `mono ./Editor/bin/Debug/Editor.exe`. It's trying to load the block files from a relative directory and they don't exist. I need to fix this.

For the moment, try:

    cd ./Editor/bin/Debug
    mono ./Editor.exe

Lemme know if that works for you.

**Comment by AshleyF** [comment]
I also just updated the `DarkGray` used for instruction words to plain `Gray`. Just noticed hardly enough contrast be seen with the default color scheme in Ubuntu.
